### ISSUE TITLE
Some bug in receiver when parsing final model

### ISSUE THREAD

**Issue by misha1sh** [chronoxor/FastBinaryEncoding#12]
Hello. Minimal size of final model struct is 8 bytes, but this assert is checking that message_size is larger than 16 bytes
https://github.com/chronoxor/FastBinaryEncoding/blob/393e6ee2528b9b53da8b0dc28d347ebb7cd5cd13/source/generator_cpp.cpp#L4513
Is this kind of bug or I am just using wrong compilation options?

**Comment by chronoxor** [comment]
8 bytes (4 byte size & 4 bytes offset) is minimal struct size, which could be included into another struct. For root structs which are send / received we need two more fields - 4 bytes total size and 4 bytes offset. See FBE spec for details - https://chronoxor.github.io/FastBinaryEncoding/documents/FBE.html#structs

![Root struct](https://github.com/chronoxor/FastBinaryEncoding/raw/master/images/struct.png)

**Comment by misha1sh** [comment]
In specification said that minimal size of FINAL struct is 8 bytes:

Final model struct properties:

Root struct size = 8 + sizeof(fileds)
Inner struct size = sizeof(fileds)

![image](https://user-images.githubusercontent.com/22164753/59962383-5d00bc00-94ed-11e9-9383-51ff7423b6b4.png)

**Comment by chronoxor** [comment]
Reproduced! Fix will be available soon.

**Comment by chronoxor** [comment]
Fixed!
