### ISSUE TITLE
Swift Question: Ho do I get  the serialized Data out of the buffer?

### ISSUE THREAD

**Issue by thieso2** [chronoxor/FastBinaryEncoding#32]
I have generated a model Visit, I want to fast serialize and then store it in a store that accepts Swift's Data() type.

What I have is:

```
let visit = Visit(number: 10)
let writer = VisitFinalModel()
try! writer.serialize(value: visit)

// I belive what I'm looking for is now in writer.buffer.data - but that is not accessible by default.
let data = writer.buffer.data

// I would now store data on disk. 

// this is how i would recreate the struct
let buf = Buffer()
buf.attach(buffer: data)
        
let reader = VisitModel()
reader.attach(buffer: buf)
let restoredModel = reader.deserialize()
``` 
Question: What's the official way to get something Data() compatible from the writer.

Thanx for this great library!

**Comment by Bort-777** [comment]
Hi,

Direct fork with data in Buffer is incapsulated. You should work with protocols, which provide access to it. 
_SenderProtocol_ - allow verify&serialise model in correct way (you could use generated `Sender: SenderProtocol` with [flag --sender](https://github.com/chronoxor/FastBinaryEncoding#senderreceiver-protocol) )  
_SenderListener_ - allow to revive back Swift's Data() type for next using (store or sent)
Example may help: https://github.com/chronoxor/FastBinaryEncoding/blob/master/projects/Swift/Tests/Examples/SendReceive.swift

**Comment by Bort-777** [comment]
Finally, for correct way, we can add public read-only access to array of bytes (in [Buffer.swift](https://github.com/chronoxor/FastBinaryEncoding/blob/master/projects/Swift/Proto/Fbe/Source/ChronoxorFbe/Buffer.swift#L14)) for consistency with C implementation, right @chronoxor ?

**Comment by thieso2** [comment]
> Hi,
> 
> Direct work with data in `Buffer` model is incapsulated. You should work with protocols, which provide access to it.
> _SenderProtocol_ - allows verify&serialise model in correct way (you could use generated `Sender: SenderProtocol` with [flag --sender](https://github.com/chronoxor/FastBinaryEncoding#senderreceiver-protocol) )
> _SenderListener_ - allows to receive back Swift's Data() type for next using (store or sent)
> Example may help: https://github.com/chronoxor/FastBinaryEncoding/blob/master/projects/Swift/Tests/Examples/SendReceive.swift

Thank you for pointing me in that direction. I can work with that!
And I was hoping that FBE had some convinience API for the "my usecase":

```
// API I *wished* existed:

// Persisting
let visit = Visit(...)
if let data : Data = try visit.asData() {
  Storage.storeVisit(data)
}

// Loading
let data : Data = Storage.readVisit(...)
let visit = try Visit(from: data)
```

I'm new to this binary serializing business and may not know the best practices.

**Comment by Bort-777** [comment]
So, you able to create your own SenderListener implementation.
```
struct VisitDataListener: SenderListener {
  let successClosure: ((Data) -> ())

  func onSend(buffer: Data, offset: Int, size: Int) throws -> Int {
    successClosure(buffer)
    return  size
  }
}

// Persisting

static let sender = Sender()
let visit = Visit(...)
sender.send(obj: visit, listener: VisitDataListener(successClosure: { data in
  Storage.storeVisit(data)
})
```
Looks good related to performance practices: without any excess manipulations

**Comment by chronoxor** [comment]
SenderListener is intended to implement communications protocols (e.g. TCP/WebSocket servers). Therefore I suggest extend Buffer class with public property to access bytes buffer, its size and capacity.

**Comment by Bort-777** [comment]
Updated in commit https://github.com/chronoxor/FastBinaryEncoding/commit/29cbf088c2863fed9a2e6ae53e07d539d469bfb4, so `buffer.data` is available now.
