### ISSUE TITLE
Cannot build domain models on ubuntu

### ISSUE THREAD

**Issue by OptoCloud** [chronoxor/FastBinaryEncoding#34]
OS:   Ubuntu 20.04
FBEC: 1.4.0.0

Im trying to build the [sample domain model](https://github.com/chronoxor/FastBinaryEncoding/blob/master/proto/proto.fbe) with the command:
```
./fbec --cpp --input=proto.fbe --output=out/.
```
however this gives me:
```
Open input file - proto.fbe...Done!

proto.fbe:5: error: syntax error
domain
     ^--- syntax error
Parsing input...Done!
Close input file...Done!
Segmentation fault (core dumped)
```
I cant find a solution to this

**Comment by tancyew** [comment]
hi i'm facing the same issue on version 1.6.0.0 on macos. Is there a workaround on this? would like to be able to add my package name to the generated file.

P/S : Awesome library! Thanks for sharing such amazing work!

**Comment by chronoxor** [comment]
Please try the most recent FBEC:
```
fbec.exe --version
1.7.0.0
```

**Comment by tancyew** [comment]
@chronoxor Appreciate the prompt reply! Will definitely give it a shot.

**Comment by tancyew** [comment]
@chronoxor it works! just have to declare domain before the package. thanks!

**Comment by OptoCloud** [comment]
I ended up using FlatBuffers instead of this, but imma close the issue since it seems to be fixed :)
