### ISSUE TITLE
Question: can you share any technical detail?

### ISSUE THREAD

**Issue by facontidavide** [chronoxor/FastBinaryEncoding#5]
Hi,

I have just found out about this library and it looks very impressive.
I am quite familiar with Flatbuffers and its implementation and I am just curious: can you share any detail about the reason why your approach outperform others that have "zero copy" deserialization?

Thanks for sharing your work.

Davide

**Comment by chronoxor** [comment]
Sometimes zero-copy is not a silver bullet. For example Flatbuffers keeps all data in memory buffer and provides getters to access fields. My approach is a little different. FBE generates native classes/structs and collections for destination languages which allows to easily describe any domain area in cross platform way. You work with native classes and then serialize/deserialize them in a very quick way - think like a cross/platform memcpy sizeof(struct)).

Additionally FBE generates zero-copy class models which allows to look into fields with getters/setters with a data serialized in buffer. It works good for scenarios when you get some data and need to have a quick look into some fields to decide where to redirect this data.

**Comment by facontidavide** [comment]
Thanks for the detials
