### ISSUE TITLE
Arbitrary length bits type supported?

### ISSUE THREAD

**Issue by tan-wei** [chronoxor/FastBinaryEncoding#6]
Thanks for this awesome project. After read the documents, I have a question about arbitrary length bits type. I think now the current status about this kind of type is unsupoorted. Am I right? If I were right (hope not), is there any plan about it? Thanks very much! Have a nice day!

**Comment by chronoxor** [comment]
No it is not supported and there is no plans to support it. You have to emulate it in upper protocols using uint8/uint16/uint32/uint64 or fixed/dynamic bytes array. For this puprose use bytes, byte[10] or byte[] type definitions in structs.

**Comment by tan-wei** [comment]
Thanks for reply. Arbitrary length bits type is seldom used indeed.
