### ISSUE TITLE
executing fbec command(C#) with multiple .fbe files gives some missing dependency errors

### ISSUE THREAD

**Issue by josep-calull** [chronoxor/FastBinaryEncoding#68]
Attached a simple vs project.
[Paragon.DoT.zip](https://github.com/chronoxor/FastBinaryEncoding/files/8729102/Paragon.DoT.zip)

For example, have a look at this file:
- Network/Messages/dot_network_messages.cs

All files were generated using this .bat file:
Run the Paragon.DoT\DoT\run-fbe.bat file and you will know what do I mean.

See if this is possible to fix or if it is better to use one BIG .fbe FILE.

Apart from that, would be nice to add support for subpackages using '.' in C#.

Thank you chronoxor.

**Comment by chronoxor** [comment]
The recommended way is to keep all fbe-proto files and generated source in one directory. I've just fix your sample. Please see attached.
[Paragon.DoT.zip](https://github.com/chronoxor/FastBinaryEncoding/files/8729351/Paragon.DoT.zip)

**Comment by chronoxor** [comment]
This is already done in Java using `domain com.chronoxor` will generate `package com.chronoxor.proto;`. I think it is possibe to do the same for C#. I'll look into it. You'll get `domain DoT` -> `namespace DoT.dot`

**Comment by josep-calull** [comment]
Would be nice if:

package DoT_Logic =>=> namespace DoT.Logic{}
package DoT_Logic_Commands =>=> namespace DoT.Logic.Commands{}

It is not essential but would be amazing. 
I'll close this thread.

Thank you very much Chronoxor.

**Comment by chronoxor** [comment]
Fixed in FBE 1.10.0.0. Please see your sample updated:
[Paragon.DoT.zip](https://github.com/chronoxor/FastBinaryEncoding/files/8733977/Paragon.DoT.zip)

**Comment by josep-calull** [comment]
I'll try it out now.
Excellent & fast support.

Thank you!

**Comment by josep-calull** [comment]
Have a look at these:
Main think I did is put a 'sub-domain' per .fbe file.
The generated code is weird.
See if it is possible to fast fix, otherwise nvm.

Thank you again Chronoxor.

[Paragon.DoT2.zip](https://github.com/chronoxor/FastBinaryEncoding/files/8737145/Paragon.DoT2.zip)

**Comment by chronoxor** [comment]
Domain should be the same for all protocols (e.g `domain DoT`). All packages should have the same level (without dots in names). This is come because we need to support lots of platforms some of them have no namespace concepts.

In you case I suggest having the following hierarchy:
```
domain DoT

package Common offset 1
package Logic offset 100
package LogicCommands offset 500
package Network offset 10000
package NetworkMessages offset 11000
```

**Comment by josep-calull** [comment]
Okey! This will work for me.
Thank for having a look Chronoxor.

**Comment by josep-calull** [comment]
Sorry to bother you again. I did what you said but.. hehe, still missing some dependencies.
[Paragon.DoT3.zip](https://github.com/chronoxor/FastBinaryEncoding/files/8737464/Paragon.DoT3.zip)

**Comment by chronoxor** [comment]
When inheriting messages/structs from import don't forger to add corresponding package prefix - `: Network.Message`

**Comment by josep-calull** [comment]
Aha!
Now It is perfeeeeeeeeeeeect!
Thanks
