### ISSUE TITLE
FBE::JSON::ChildNodeReader small bug with RapidJson v1.1.0

### ISSUE THREAD

**Issue by PengyiPan** [chronoxor/FastBinaryEncoding#72]
Using latest RapidJson [v1.1.0](https://github.com/Tencent/rapidjson/releases/tag/v1.1.0)

In the generate fbe_json.h, under struct ChildNodeReader,  the last line should be 

```cpp
... member->value.GetObject(), ...
instread of
... member->value.GetObj(), ...
```

Cheers

**Comment by chronoxor** [comment]
Thanks for reporting! Fixed in 1.12.0.0
