### ISSUE TITLE
C++ FinalClient::request small bug

### ISSUE THREAD

**Issue by PengyiPan** [chronoxor/FastBinaryEncoding#73]
This should be easy to reproduce, using latest fbec 1.11.0.0 with --cpp --final --proto

The generated FinalClient::request(..) methods has
```cpp
size_t serialized = Sender::send(value);
```
which my gcc 11 compiler complains
Fixed by changing to
```cpp
size_t serialized = FinalSender::send(value);
```

btw, really awesome library!

**Comment by chronoxor** [comment]
Thanks for reporting! Fixed in 1.12.0.0
