### ISSUE TITLE
C# generated code doesn't generate Send Method

### ISSUE THREAD

**Issue by M0n7y5** [chronoxor/FastBinaryEncoding#77]
I followed your documentation and i generated C++ code and C# code. However for some reason send  method is not generated in C# code.
![obrazek](https://user-images.githubusercontent.com/17201053/200195315-f7441c91-cc6d-4bf2-a9df-2a8b680892a7.png)

Same proto is used for C++ and C++ was generated without any problems.

Here is the proto

```protobuf
/*
   Protocol description
*/

// Domain declaration
domain com.example

// Package declaration
package proto

// Protocol version
version 1.0

enum LoginResponseCode : byte
{
    Error;
    Success;
    WrongPassOrName;
    Banned;
}

struct BaseMessage
{
    //this id is for response
    [key] int32 responseId;
    bool fireAndForget;
}

struct LoginRequest
{
    string name;
    string pass;
}

struct LoginResult
{
    string name;
    string pass;
}

// Login message declaration
message LoginMessage
{
    LoginRequest login;
}

```

Thank you in advance.

**Comment by chronoxor** [comment]
Please look into [simple.fbe](https://github.com/chronoxor/NetCoreServer/blob/master/proto/simple.fbe) and corresponding [Server](https://github.com/chronoxor/NetCoreServer/tree/master/examples/ProtoServer) and [Client](https://github.com/chronoxor/NetCoreServer/tree/master/examples/ProtoClient) C# examples.

**Comment by M0n7y5** [comment]
You should then update main readme

**Comment by M0n7y5** [comment]
For some reason i need tho implement this constructor, but in your example you are not doing that. Is that a bug?
![obrazek](https://user-images.githubusercontent.com/17201053/200196576-6d379211-fc20-4980-b9c6-cf6f0bf592a9.png)

**Comment by M0n7y5** [comment]
You have this. 
![obrazek](https://user-images.githubusercontent.com/17201053/200196638-6774c6bc-7a03-4f18-b731-bc8b658a5dd9.png)

**Comment by M0n7y5** [comment]
Looks like i fixed it by adding correct usings.
