### ISSUE TITLE
Any plans for async support for C#?

### ISSUE THREAD

**Issue by M0n7y5** [chronoxor/FastBinaryEncoding#78]
Are there any plans for proper asynchronous support for C# using TAP based paradigm?

**Comment by chronoxor** [comment]
Generated Client has Request() methods that return Task and possible to provide a timeout for request:
```
public Task<SimpleResponse> Request(SimpleRequest value) {...}
public Task<SimpleResponse> Request(SimpleRequest value, TimeSpan timeout) {...}
```

For the Server you only have to override the corresponding message handler and answer with a corresponding response or reject in a reasonable time:
```
        public void OnReceive(SimpleRequest request) 
        {
            Console.WriteLine($"Received: {request}");

            // Validate request
            if (string.IsNullOrEmpty(request.Message))
            {
                // Send reject
                SimpleReject reject = SimpleReject.Default;
                reject.id = request.id;
                reject.Error = "Request message is empty!";
                Sender.Send(reject);
                return;
            }

            // Send response
            SimpleResponse response = SimpleResponse.Default;
            response.id = request.id;
            response.Hash = (uint)request.Message.GetHashCode();
            response.Length = (uint)request.Message.Length;
            Sender.Send(response);
        }
    }
```

**Comment by M0n7y5** [comment]
yeah but for C# server ... OnSend cant be async 
![obrazek](https://user-images.githubusercontent.com/17201053/200200731-00047c35-945a-4119-a068-c82cd5859c03.png)

**Comment by chronoxor** [comment]
On the server side just think that `Sender.Send(response);` will not block and complete immediately so you don't need async/await and return Task (it will always completed). Your message will be serialized and placed into send buffer and send to the client ASAP. You only need to control that server produces not more data than can be transferred over network bandwidth and consumed by the client. Also you can disconnect slow clients by checking BytesPending property (e.g. not much than 10mb per session).

**Comment by M0n7y5** [comment]
Session.Send is doing additional work like encryption that is asynchronous. This basically forces me to get that buffer and save it to some Queue first and then asynchronously process messages that needs to be sent.
