### ISSUE TITLE
Switch out std::optional with tl::optional

### ISSUE THREAD

**Issue by adrianduke** [chronoxor/FastBinaryEncoding#82]
According to the docs: https://github.com/TartanLlama/optional - `tl::optional` is API compatible with `std::optional` however it supports c++11 onwards. According to your docs, this is the only dependency preventing this project compiling with an older c++ version.

To your knowledge would switching this dependency make this project at least c++14 compatible?

**Comment by chronoxor** [comment]
I think it's easy to check - just search & replace "std::optional" -> "tl::optional" in generated FBE C++ code and include "[tl/optional.hpp](https://github.com/TartanLlama/optional/blob/master/include/tl/optional.hpp)" in fbe.h

As I remember no other C++17 features are used in FBE
