### ISSUE TITLE
Is there a specific reason to undef HOST_NOT_FOUND?

### ISSUE THREAD

**Issue by MrJia1997** [chronoxor/FastBinaryEncoding#94]
Just wonder. Is there a specific reason to undef HOST_NOT_FOUND? What's the problem if it's still defined?

https://github.com/chronoxor/FastBinaryEncoding/blob/b1f5223846c76ae909d720a83099fff1ffdd5da6/proto/fbe.h#L44

**Comment by chronoxor** [comment]
Quick answer - we have HOST_NOT_FOUND duplicate in one of our projects and we want a quick solution for this issue)
![image](https://github.com/chronoxor/FastBinaryEncoding/assets/4397805/cc14bf14-5d9a-45b5-b0f4-cbbbc04cea72)

**Comment by chronoxor** [comment]
But other definitions from Winapi.h must be undefined anyway, because they are duplicates even with std libraries (e.g. std::min, std::max):

#undef DELETE
#undef ERROR
#undef Yield
#undef min
#undef max
#undef uuid_t

**Comment by MrJia1997** [comment]
Thank you for your prompt response! The reason why I ask this is that `HOST_NOT_FOUND` is also used in `netdb.h` on Linux, and undefine it will cause some other libraries to not work, e.g., Asio.

**Comment by chronoxor** [comment]
Probably I'll remove it soon. Thanks for pointing on this!

**Comment by chronoxor** [comment]
Fixed in FBE 1.14.5.0
