### ISSUE TITLE
Bug in the generated C# code when building final model - vector of structs

### ISSUE THREAD

**Issue by alandemaria** [chronoxor/FastBinaryEncoding#95]
For the following schema:
```
domain TestDomain

package TestClient

version 1.0

struct Field1 
{
   uint64 Whatever;
}

message Field2 
{
    Field1[] ListOfWhatever;
}
```

The generated C# code presents errors when building with --final flag.

In the `public long Get(out HashSet<T> values)` method of the following classes: 
- `FinalModelVectorValueType`
- `FinalModelVectorReferenceType`
- `FinalModelVectorOptionalReferenceType`
- `FinalModelVectorOptionalValueType`

For this this line of code

`values = new HashSet<T>((int)fbeVectorSize);`

The error says:

`Error CS1503 Argument 1: cannot convert from 'int' to 'System.Collections.Generic.IEnumerable<T>'`

The generic constructor of `HashSet` doesn't expect a capacity parameter. Leaving the call parameterless solves the issue:

`values = new HashSet<T>();`

I'm using the latest version of the package.

**Comment by chronoxor** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.-ctor?view=net-8.0#system-collections-generic-hashset-1-ctor(system-int32)
```c#
// Initializes a new instance of the HashSet<T> class that is empty, 
// but has reserved space for capacity items and uses the default 
// equality comparer for the set type.
public HashSet (int capacity);
```

**Comment by alandemaria** [comment]
Sure thing, I was targeting .NET Standard 2.0. Problem goes away in .NET Standard 2.1.

Thank you
