### ISSUE TITLE
Generated code usage

### ISSUE THREAD

**Issue by OliverFendt** [chronoxor/FastBinaryEncoding#98]
This is a request for clarification:
In case I use it for serialization, can I use the generated source code and the other generated artifacts without restriction? Or do I have to put the MIT license into the generated code and your copyright notice? I do not believe so, but I want to be sure and thus I am asking.

**Comment by chronoxor** [comment]
Yes of course! As you created a fbe file, it's yours and all generated models are yours as well. You could put any license or copyright on them.

Only fbe sources and fbe tool goes with a MIT license.

**Comment by OliverFendt** [comment]
@chronoxor thank you very much for the clarification
